# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build custom-cards-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t custom-cards-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system custom-cards-api && \
          adduser --system -G custom-cards-api custom-cards-api

COPY dist/custom-cards-api custom-cards-api
RUN chown -R custom-cards-api:custom-cards-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix custom-cards-api --omit=dev -f install

CMD [ "node", "custom-cards-api" ]
